# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dvsmb_qtNF4_422z4Pfv6uRYtafelCY
"""

import random

moneyWin =  [10000 , 100000 ,3000, 10000000, 10 , 6000 , 1234, 34868, 100 , 50000, 700000, 1]


class atm(object):

  def __init__(self, cardNumber, pinNumber, balance):
    self.cardNumber = cardNumber
    self.pinNumber = pinNumber
    self.balance = balance

  def Login(self):
      global l
      l = 0
      cardNumberEntered = int(input("Please enter card number: "))
      pinNumberEntered = int(input("Please enter pin number: "))

      if cardNumberEntered == self.cardNumber and   pinNumberEntered == self.pinNumber:
        print("Succesfully authenticated!")
        l = l + 1
        

      else: 
        print("Failed to authenticate")

  def cashWithDrawl(self):

      cash = int(input("Please enter the amount you want to draw: "))

      if cash <= self.balance and cash%100 == 0:
        self.balance = self.balance - cash
        print("You collected " + str(cash) + "$ . So now you have " + str(self.balance) + "$ in your account" )

      elif cash % 100 != 0:
        print("You can only draw amounts which are multiples of 100")
      else:
        print("your have only" + str(balance) + "$ in your account")

  def showBalance(self): 
      print("Your balance is " + str(self.balance) + "$")

  def getPaid(self):
      r = random.choice(moneyWin)
      self.balance = self.balance + r
      print("Your boss paid you " + str(r)+"$ . So now you have " + str(self.balance) + "$ in your account")

  def launchSystem(self):
    self.Login()
    if l > 0:
      self.showBalance()
      self.cashWithDrawl()
      self.getPaid()
      print("Thank You for using me!")
  
    else:
      print("You cannot continue without authenticating into your account")


users = [user1,user2]
user1 = atm(3102,2332,1500000)
user1.launchSystem()